CREATE TABLE `songs` (`albumLink` VARCHAR(120), `artistName` VARCHAR(40), `songName` VARCHAR(40), `genre` VARCHAR(10), `songLength` VARCHAR(10) );
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/files/styles/top_cover/public/media/bb28-Philanthropy-2016-3-billboard-pio-225.jpg","The Chainsmokers ","Closer","Rock","5:16");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q56523k8p5q.jpg","Zay Hilfigerrr ","Starboy","Hip-Hop","2:16");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q58043g71qu.jpg","Hailee Steinfeld ","Heathens","Pop","4:34");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q59697htfhi.jpg","Maroon 5 ","Let Me Love You","Rock","3:12");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q55963rka7z.jpg","Drake","Broccoli","Rock","2:47");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q59123tine7.jpg","Weeknd","24K Magic","Hip-Hop","4:43");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q39056czrzc.jpg","Twenty One Pilots ","Side To Side","Hip-Hop","3:27");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q58635xjm0i.jpg","Dj Snake ","Cold Water","Country","3:20");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q58396y87pz.jpg","Dram","Juju On That Beat (TZ Anthem)","Rock","4:21");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q59725qvpol.jpg","Bruno Mars ","I Hate U I Love U","Hip-Hop","4:57");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/yyyy8029153055372258969.jpg","Ariana Grande ","Treat You Better","Pop","3:57");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q37570nx70w.jpg","Major Lazer ","Cheap Thrills","Hip-Hop","3:53");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q45858cetff.jpg","Zay Hilfigerrr ","Don&#039;t Wanna Know","Hip-Hop","5:53");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q54451rbcic.jpg","Gnash","Starving","Country","2:29");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q48642a2jvd.jpg","Shawn Mendes ","Gold","Hip-Hop","5:19");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q59697htfhi.jpg","Sia","Black Beatles","Country","4:57");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q58043g71qu.jpg","Maroon 5 ","Don&#039;t Let Me Down","Hip-Hop","5:37");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q50462hj2sc.jpg","Hailee Steinfeld ","This Is What You Came For","Hip-Hop","5:33");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/yyyy2384373149827834455.jpg","Kiiara","The Greatest","Rock","2:22");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q56523k8p5q.jpg","Rae Sremmurd ","Ride","Pop","4:37");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q37000tpld3.jpg","The Chainsmokers ","Can&#039;t Stop The Feeling!","Hip-Hop","3:33");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q48642a2jvd.jpg","Calvin Harris ","OOOUUU","Rock","3:36");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q39056czrzc.jpg","Sia","One Dance","Rock","5:52");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q34327sud67.jpg","Twenty One Pilots ","Fake Love","Pop","5:44");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q55963rka7z.jpg","Justin Timberlake ","Caroline","Rock","5:31");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q55963rka7z.jpg","Young M ","Send My Love (To Your New Lover)","Country","2:28");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/yyyy7891934543737803251.jpg","Drake","Unsteady","Hip-Hop","5:57");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q42396myajr.jpg","Drake","Needed Me","Pop","3:30");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q37409dqics.jpg","Amine","Luv","Hip-Hop","2:45");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q55103nkulw.jpg","Adele","Scars To Your Beautiful","Country","2:36");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q56666jbafk.jpg","X Ambassadors ","Sucker For Pain","Hip-Hop","4:14");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q58048p3kyi.jpg","Rihanna","Hallelujah","Country","2:25");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q52102onwz2.jpg","Tory Lanez ","Too Good","Rock","5:44");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q59089kzfpe.jpg","Alessia Cara ","Sit Still, Look Pretty","Country","3:45");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q55963rka7z.jpg","Lil Wayne ","We Don&#039;t Talk Anymore","Pop","4:44");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q59494clmoj.jpg","Pentatonix","Hymn For The Weekend","Pop","2:36");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q46483ubdhf.jpg","Drake","Tiimmy Turner","Country","5:29");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q44977u7wlb.jpg","Daya","Sneakin&#039;","Rock","4:11");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q58027oq2us.jpg","Charlie Puth ","Setting The World On Fire","Country","2:17");
INSERT INTO `songs` (`albumLink`, `artistName`, `songName`, `genre`, `songLength`) VALUES("http://www.billboard.com/images/pref_images/q55963rka7z.jpg","Coldplay","Chill Bill","Rock","3:49");

